### ISSUE TITLE
The tax goes to the balance of another player

### ISSUE THREAD

**Issue by dimeetrue** [Portal2001/Paper-currency_Banknote#1]
Hello. Is it possible to add a function so that the tax goes to the balance of another player, so that the money does not disappear (for economic servers) sorry English is not native

**Comment by Portal2001** [comment]
sure can so,
can you explain more like to whom should the tax go for example
a player did withdraw for 100 then the balance is reduced from the balance then he redeemed so the tax so to which player
1. note creater
2. not redeemer
3. or some on else?
or do you want to disable the tax?

**Comment by Portal2001** [comment]
support from GitHub is a bit slow due to obvious reasons use Discord if needed

**Comment by dimeetrue** [comment]
I understand that it is difficult to make a database. I will be grateful if you do this: 2 independent players and one server account (taxes go to it, let's say from a plugin to an automatic shop with chests), but I want the paper currency to go there as well by type:
SERVER_ECONOMY_ACCOUNT: "nickname"
SERVER_ECONOMY_ACCOUNT_UUID: "00000000-0000-0000-0000-000000000000"
SERVER_TAX_AMOUNT: 16

**Comment by Portal2001** [comment]
ok let me make it simple just confirm thats you want or correct me if wrong
1. you need a database for all taxes ok
2. 3 tax accounts which are 2 players(note creator and redeemer) 1 server  

so, ok understood that much so when the tax goes to whom is not mentioned
so let me assume some situations like:  
1. when note creator and redeemer are same (then tax goes to server)
2. when note creator and redeemer are different (then tax goes to note creator)
but it might not be good for gameplay as players can save money from paying other player due to tax

**Comment by dimeetrue** [comment]
I'll explain it easier. Now the taxes disappearing into the void. I want the country's budget to be replenished from all server transactions. So if the sender and recipient are different, the tax goes to the budget. What about whether the tax will be levied if the accounts are the same, it doesn't matter to me if not - cool, if yes I will justify it with a commission for cash withdrawal at an ATM)))

**Comment by dimeetrue** [comment]
The most important thing! The tax never goes to the sender or the recipient. They are only part of the tax system

**Comment by Portal2001** [comment]
ah ya it's simple 
1. an account for server which will have taxes (and I don't know what you mean by country's budget)
2. if note creator and redeemer is same then no tax
3. if both are different then tax goes to server

**Comment by dimeetrue** [comment]
The budget of the country (this is a Role Play) for the economic server) And so everything is correct, I will be glad if you add. Thanks for the work.

**Comment by Portal2001** [comment]
ok sure so I will prioritize this and the next update will be within 24h

**Comment by Portal2001** [comment]
@dimeetrue  the update is pushed i hope you will like it dont forget to rate the plugin 5 star
 i am closing this if got more to say open new one 😄
